# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='job_number',
            field=models.CharField(default=0, max_length=50, verbose_name='\u5de5\u53f7'),
        ),
    ]
