# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-25 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210325_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_pass',
        ),
    ]
